/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaEscritorio;

import controlador.ControladorProcesadoraPedido;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author diecu
 */
public class VistaProcesadoraPedido extends javax.swing.JDialog {

    ControladorProcesadoraPedido controlador;
    
    /**
     * Creates new form VistaProcesadoraPedido
     */
    public VistaProcesadoraPedido(java.awt.Frame parent, boolean modal,Conexion conexion) {
        super(parent, modal);
        initComponents();
        this.controlador = new ControladorProcesadoraPedido(this,conexion);
        setLocationRelativeTo(null);
        setTitle("Gestor -"+conexion.getUsuario().getNombreCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.controlador.logout();
    }//GEN-LAST:event_formWindowClosing

    public void mostrarError(String message) {
        JOptionPane.showConfirmDialog(this, message);
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
