/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaEscritorio;

import controlador.ControladorProcesadoraPedido;
import controlador.VistaProcesadoraPedidoInterface;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import modelo.Fachada;
import modelo.ItemServicio;
import modelo.UnidadProcesadora;

/**
 *
 * @author diecu
 */
public class VistaProcesadoraPedido extends javax.swing.JDialog implements VistaProcesadoraPedidoInterface {

    private ControladorProcesadoraPedido controlador;
    private ArrayList<ItemServicio> itemsSinProcesar;

    /**
     * Creates new form VistaProcesadoraPedido
     */
    public VistaProcesadoraPedido(java.awt.Frame parent, boolean modal, Conexion conexion) {
        super(parent, modal);
        initComponents();
        this.controlador = new ControladorProcesadoraPedido(this, conexion);
        this.itemsSinProcesar = null;
        setLocationRelativeTo(null);
        setTitle("Gestor -" + conexion.getUsuario().getNombreCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTItemsSinProcesar = new javax.swing.JTable();
        btnTomarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTItemsSinProcesar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Observaciones", "Nro mesa", "Mozo"
            }
        ));
        jScrollPane2.setViewportView(jTItemsSinProcesar);

        btnTomarPedido.setBackground(new java.awt.Color(76, 35, 64));
        btnTomarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTomarPedido.setText("Tomar Pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTomarPedido)
                .addContainerGap(307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.controlador.logout();
    }//GEN-LAST:event_formWindowClosing

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showConfirmDialog(this, msg);
    }

    @Override
    public void actualizarYMostrsarItemsSinProcesar(ArrayList<ItemServicio> items) {
        this.itemsSinProcesar = items;
        DefaultTableModel datos = new DefaultTableModel();
        jTItemsSinProcesar.removeAll();
        int contador = 0;
        for (ItemServicio i : this.itemsSinProcesar) {
            datos.setValueAt(i.getProducto().getNombre(), contador, 0);
            datos.setValueAt(i.getCantidad(), contador, 1);
            datos.setValueAt(i.getDescripcion(), contador, 2);
            datos.setValueAt(i.getServicio().getMesa().getNumero(), contador, 3);
            datos.setValueAt(i.getServicio().getMesa().getMozo().getNombreCompleto(), contador, 4);

            contador++;
        }
        jTItemsSinProcesar.setModel(datos);
    }
    
    @Override
    public void elegirUnidadProcesadora(ArrayList<UnidadProcesadora> unidades) {
        JOptionPane.showInputDialog(this, "Seleccione unidad a trabajar: ",
            "UNIDADES PROCESADORAS", JOptionPane.QUESTION_MESSAGE, null,
            unidades.toArray(), "");
    }

            /**
             * @param args the command line arguments
             */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTItemsSinProcesar;
    // End of variables declaration//GEN-END:variables
}
