/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaEscritorio;

import controlador.ControladorProcesadoraPedido;
import controlador.VistaProcesadoraPedidoInterface;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import modelo.ItemServicio;

/**
 *
 * @author diecu
 */
public class VistaProcesadoraPedido extends javax.swing.JDialog implements VistaProcesadoraPedidoInterface {

    private ControladorProcesadoraPedido controlador;
    private ArrayList<ItemServicio> itemsSinProcesar;
    private ArrayList<ItemServicio> itemsTomados;

    /**
     * Creates new form VistaProcesadoraPedido
     */
    public VistaProcesadoraPedido(java.awt.Frame parent, boolean modal, Conexion conexion) {
        super(parent, modal);
        initComponents();
        this.controlador = new ControladorProcesadoraPedido(this, conexion);
        setTitle("Gestor -" + conexion.getUsuario().getNombreCompleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tPedidos = new javax.swing.JTable();
        btnTomarPedido = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tPedidosTomados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Observaciones", "Nro mesa", "Mozo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tPedidos.setName(""); // NOI18N
        tPedidos.setSelectionBackground(new java.awt.Color(102, 0, 102));
        tPedidos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tPedidos);
        if (tPedidos.getColumnModel().getColumnCount() > 0) {
            tPedidos.getColumnModel().getColumn(0).setResizable(false);
            tPedidos.getColumnModel().getColumn(1).setResizable(false);
            tPedidos.getColumnModel().getColumn(2).setResizable(false);
            tPedidos.getColumnModel().getColumn(3).setResizable(false);
            tPedidos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnTomarPedido.setBackground(new java.awt.Color(76, 35, 64));
        btnTomarPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTomarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnTomarPedido.setText("Tomar Pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        tPedidosTomados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Observaciones", "Nro mesa", "Mozo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tPedidosTomados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tPedidosTomados.setName(""); // NOI18N
        tPedidosTomados.setSelectionBackground(new java.awt.Color(102, 0, 102));
        tPedidosTomados.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(tPedidosTomados);
        if (tPedidosTomados.getColumnModel().getColumnCount() > 0) {
            tPedidosTomados.getColumnModel().getColumn(0).setResizable(false);
            tPedidosTomados.getColumnModel().getColumn(1).setResizable(false);
            tPedidosTomados.getColumnModel().getColumn(2).setResizable(false);
            tPedidosTomados.getColumnModel().getColumn(3).setResizable(false);
            tPedidosTomados.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTomarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTomarPedido)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.controlador.logout();
    }//GEN-LAST:event_formWindowClosing

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
        // TODO add your handling code here:
        int posItem = tPedidos.getSelectedRow();
        if (posItem != -1) {
            controlador.pedidoTomado(itemsSinProcesar.get(posItem));
        } else {
            controlador.pedidoTomado(null);
        }
        /**
         * DUDA SI ESTA BIEN EL IF ACA
         */
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    @Override
    public void mostrarError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    @Override
    public void mostrarItemsSinProcesar(ArrayList<ItemServicio> items) {
        itemsSinProcesar = items;
        mostrarTablaPedidos(items, tPedidos);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tPedidos;
    private javax.swing.JTable tPedidosTomados;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarPedidosTomados(ArrayList<ItemServicio> items) {
        itemsTomados = items;
        mostrarTablaPedidos(items, tPedidosTomados);
    }

    private void mostrarTablaPedidos(ArrayList<ItemServicio> items, javax.swing.JTable tabla) {
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Producto");
        datos.addColumn("Cantidad");
        datos.addColumn("Observaciones");
        datos.addColumn("Nro mesa");
        datos.addColumn("Mozo");
        datos.setRowCount(items.size());
        int contador = 0;
        for (ItemServicio i : items) {
            datos.setValueAt(i.getProducto().getNombre(), contador, 0);
            datos.setValueAt(i.getCantidad(), contador, 1);
            datos.setValueAt(i.getDescripcion(), contador, 2);
            datos.setValueAt(i.getServicio().getMesa().getNumero(), contador, 3);
            datos.setValueAt(i.getServicio().getMesa().getMozo().getNombreCompleto(), contador, 4);

            contador++;
        }
        tabla.setModel(datos);
    }
}
